config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resource :accounts
  match '/courses/new', to: 'courses#create', via: :post
  match '/courses/edit/:course_id', to: 'courses#edit', via: :get, :as => 'edit_course'
  match '/courses/edit', to: 'courses#edit', via: :post
  resource :courses
end

app/models/account.rb
class Account < ApplicationRecord
  attr_accessor :password
#  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
#  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :course_title, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :subject_title, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :subject_course, :presence => true, :length => { :in => 3..20 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    def index
        
    end
    
  def new
    @account = Account.new 
  end
  
  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    
    render "new"
  end
  
  
    def account_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:account).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @courses=Course.all
  end
  def new
    @course=Course.new
  end
  def create
    @course=Course.create(course_params)
    if @course.save
      redirect_to :action => 'show'
    else
      render :action => 'new'
    end
  end
  def course_params
    params.fetch(:course, {}).permit(:course_title)
  end
  def edit
    @course=Course.find(params[:course_id])
  end
  def update
    @course=Course.find_by_id(params[:course_idt])
    if @course.update_attributes(course_params)
      redirect_to :action => 'show'
    else
      render :action => 'edit'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/new.html.haml
-#= form_tag accounts_path do
-#    
-#    = label :accounts, :name, 'Username:'
-#    = text_field :accounts, :name
-#    
-#    = label :accounts, :password, 'Password:'
-#    = password_field :accounts, :password
-#
-#    = submit_tag 'Login'
//link to stylesheet local and online bootstrap
%meta{:charset => "utf-8"}
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
%link{:rel => :stylesheet, :type => :"text/css", :href => "/assets/css/application.css"}
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
%script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

%body.container
  %h1 UserAuth | Signup
  %div{:class => "Sign_Form"}
    %h1 Create a faculty Account
    = form_for(:account, :url => {controller: 'accounts', action: 'create'}) do |f|
      = f.label :name, 'Username:'
      = f.text_field :name
       
      = f.label :password, 'Password:'
      = f.password_field :password
      -#%p Email: = f.text_field :email

      = f.label :password, 'Password Confirmation:'
      = f.password_field :password_confirmation
      
      = f.submit :Signup
//ayad ko la an notice
  %ul{:class => "Sign-up Notice"}
    %p Notice
    - if @account.errors.any?
      - @account.errors.full_messages.each do |msg|
        %li= msg
      %li= flash[:notice]
    - elsif !@account.errors.any?
      %li= flash[:notice]

app/views/courses/edit.html.haml
%h1 Edit Course
%body
= form_for(:course, :url => {controller: 'courses', :action => 'update'}) do |f|

  = f.label :course_title, 'Title:'
  = f.text_field :course_title, :value => @course.course_title
  = f.hidden_field :course_idt, value: @course.id
  = f.submit :Update

app/views/courses/new.html.haml
%h1 Add New Course
%body
= form_for(:course, :url => {controller: 'courses', :action => 'create'}) do |f|

  = f.label :course_title, 'Title:'
  = f.text_field :course_title

  = f.submit :Create

app/views/courses/show.html.haml
%ul.nav.nav-tabs.nav-stacked
%h1 Prospectus Management
%body
  -@courses.each do |course|
    %li= course.course_title
    = link_to 'Edit Course', edit_course_path(:course_id => course.id)

= button_to 'Add Prospectus',new_courses_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Prospectus
    = csrf_meta_tags

    = stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'default', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/welcome/index.html.haml
%meta{:charset => "utf-8"}
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
%link{:rel => :stylesheet, :type => :"text/css", :href => "/assets/css/application.css"}
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
%script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

%body.container
	%h1 UPVTC Prospectus
	%ul
		= button_to "Sign up", new_accounts_path , :class => "click", :method => :get
		= button_to "Sign in" #sign in button